### ISSUE TITLE
index.bsi

### ISSUE THREAD

**Issue by BetaMaax** [BSData/mordheim#14]
Server issues downloading the index.bmi for the Mordheim data from:
http://battlescribedata.appspot.com/repos/mordheim/index.bsi

**Comment by amis92** [comment]
I suppose that was because of failing to load Witch Hunters file (probably threw exception in server execution engine, failing to provide correct index file). I've now corrected it, on the next data refresh all should work as expected (it means a couple of hours).

Cheers for the tip!
