### ISSUE TITLE
[Anon] Bug report: Possessed.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#22]
**File:** Possessed.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** I think in the list for the Possessed, there is a "points" mistake for the mutation option "tentacle" on the "Possessed". In the roster, it costs 70 pts while in the rulebook it is only 30 pts.
Thank you,
Guillaume

**Comment by dabrown** [comment]
Changed cost from 70 pts to 35 pts... didn't think I'd check did you? Fix is in the pipelines.

http://www.thekeeponline.com/documents/MordheimLivingRulebook.pdf
