### ISSUE TITLE
[Anon] Bug report: High_Elf_Shadow_Warriors.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#23]
**File:** High_Elf_Shadow_Warriors.catz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Getting ork mob magic instead of shadow magic. When I create a shadow warrior warband

**Comment by dabrown** [comment]
Gotta keep those greens away from the keyboard... too much copa/pasta! Fix is in the pipelines.
