### ISSUE TITLE
[Anon] Bug report: Middenheim_Mercinaries.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/mordheim#48]
**File:** Middenheim_Mercinaries.catz

**BattleScribe version:** 2.00.18

**Platform:** Android

**Dropbox:** No

**Description:** When creating a warband, there are no forces to add. Seems to have broken in the last couple of weeks.

**Comment by gandalf78** [comment]
Have you tried the last version of the app? Please check it and try again

**Comment by Irian81** [comment]
Old issue not reproducible anymore
