### ISSUE TITLE
New Armies

### ISSUE THREAD

**Issue by twizted86** [BSData/mordheim#7]
Does anyone monitor this that is able to add new armies? I'm particularly interested in Lizardmen and Beastmen. Any help would be appreciated.

**Comment by 00arak00** [comment]
I was working on it but kind of got sidetracked once all the armies we play locally. Will look into it but the layout is pretty basic if you want to clone one of the armies and then modify. It is how I learneded

**Comment by twizted86** [comment]
Thanks,  I'll take a look at it.

**Comment by dabrown** [comment]
@twizted86 Lizardmen warband added, give it a go! That group is awkward, let me know if you run into issues.  I still need to put it's poison variances into the roster so I'll be back to fix any errors you find.

**Comment by twizted86** [comment]
Thanks, I'll give it a try when incomes through. I also spent some time work in on the Beastmen Raiders, how do I go about uploading it for others to use?

**Comment by dabrown** [comment]
Here's the video describing the process: BattleScribe Data Files GitHub: http://youtu.be/Hs4PoNTwNAA
