### ISSUE TITLE
Weird pit fighter / witch hunter bug

### ISSUE THREAD

**Issue by Uncle-Mel** [BSData/mordheim#93]
**Describe the bug**
When adding hired swords, there seem to be "conflicts" between warband members and hired swords

**To Reproduce**
1 Add hired sword characters and (I tested with) witchhunters warband
2 Add pit fighter and basic witch hunter band
3 the standard "witch hunter" conflicts with the pit fighter and there is an error that there is 1 too many pit fighter present (adding witch hunters increases this number)
4 after this, there is always an error that there are too many pit fighters even if there are none, when adding more than one witch hunter

P.S. This also happens with Warlock/Warrior priest combo

**Comment by Uncle-Mel** [comment]
Did some more testing: 

Skaven:
Black skaven/warlock
Eshin Sorcerer/Pit fighter
Rat Ogre/Freelancer
Verminkin/Halfling Scout

Posessed:
mutants/Warlock
Posessed/pit fighter
Beastmen/Halfling Scout
brethren/Freelancer


The issue seems to be with just those 4 hired swords:
-Pit Fighter
-Warlock
-Halfling Scout
-Freelancer

**Comment by Irian81** [comment]
Guess this migth be due to duplicated IDs will try and fix them now but no guarantees migth become messy
